AWSTemplateFormatVersion: '2010-09-09'
Description: Cognito User Pool and Client for Growksh website

Parameters:
  Environment:
    Type: String
    Default: dev

    Description: Environment name

Resources:
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub 'growksh-website-pool-${Environment}'
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: false
          RequireLowercase: false
          RequireNumbers: false
          RequireSymbols: false
      Schema:
        - Name: email
          AttributeDataType: String
          Mutable: true
          Required: true
        - Name: name
          AttributeDataType: String
          Mutable: true
        - Name: phone_number
          AttributeDataType: String
          Mutable: true
      UserAttributeUpdateSettings:
        AttributesRequireVerificationBeforeUpdate:
          - email
      LambdaConfig:
        PreSignUp: !ImportValue
          Fn::Sub: 'growksh-website-${Environment}-pre-sign-up-arn'
        CustomMessage: !ImportValue
          Fn::Sub: 'growksh-website-${Environment}-custom-message-arn'
        DefineAuthChallenge: !ImportValue
          Fn::Sub: 'growksh-website-${Environment}-define-auth-challenge-arn'
        CreateAuthChallenge: !ImportValue
          Fn::Sub: 'growksh-website-${Environment}-create-auth-challenge-arn'
        VerifyAuthChallengeResponse: !ImportValue
          Fn::Sub: 'growksh-website-${Environment}-verify-auth-challenge-arn'
        PostConfirmation: !ImportValue
          Fn::Sub: 'growksh-website-${Environment}-post-confirmation-arn'

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub 'growksh-website-client-${Environment}'
      UserPoolId: !Ref UserPool
      ExplicitAuthFlows:
        - ALLOW_CUSTOM_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      PreventUserExistenceErrors: ENABLED
      AllowedOAuthFlows: []
      ReadAttributes:
        - email
        - name
        - phone_number

Outputs:
  UserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref UserPool
    Export:
      Name: !Sub 'growksh-website-${Environment}-pool-id'

  UserPoolArn:
    Description: Cognito User Pool ARN
    Value: !GetAtt UserPool.Arn
    Export:
      Name: !Sub 'growksh-website-${Environment}-pool-arn'

  UserPoolClientId:
    Description: Cognito User Pool Client ID
    Value: !Ref UserPoolClient
    Export:
      Name: !Sub 'growksh-website-client-${Environment}-id'
