AWSTemplateFormatVersion: '2010-09-09'
Description: S3 bucket for static site assets

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, prod, ephemeral]
    Description: Environment name
  BucketName:
    Type: String
    Description: S3 bucket name (must be globally unique)

Resources:
  StaticSiteBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      BucketName: !Ref BucketName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: growksh-website

  StaticSiteOriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub 'growksh-${Environment}-oac'
        Description: OAC for CloudFront to access private S3 bucket
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  StaticSiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref StaticSiteBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowCloudFrontReadOnly
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !Sub '${StaticSiteBucket.Arn}/*'
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub 'arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistribution}'

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Comment: !Sub 'Growksh website ${Environment}'
        DefaultRootObject: index.html
        PriceClass: PriceClass_100
        HttpVersion: http2
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt StaticSiteBucket.RegionalDomainName
            S3OriginConfig: {}
            OriginAccessControlId: !Ref StaticSiteOriginAccessControl
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
          Compress: true
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
        CustomErrorResponses:
          - ErrorCode: 403
            ResponsePagePath: /index.html
            ResponseCode: 200
            ErrorCachingMinTTL: 0
          - ErrorCode: 404
            ResponsePagePath: /index.html
            ResponseCode: 200
            ErrorCachingMinTTL: 0
        ViewerCertificate:
          CloudFrontDefaultCertificate: true
        Restrictions:
          GeoRestriction:
            RestrictionType: none

Outputs:
  BucketName:
    Description: S3 bucket name
    Value: !Ref StaticSiteBucket
    Export:
      Name: !Sub 'growksh-${Environment}-bucket'

  BucketArn:
    Description: S3 bucket ARN
    Value: !GetAtt StaticSiteBucket.Arn
    Export:
      Name: !Sub 'growksh-${Environment}-bucket-arn'

  CloudFrontDistributionId:
    Description: CloudFront distribution ID
    Value: !Ref CloudFrontDistribution
    Export:
      Name: !Sub 'growksh-${Environment}-cloudfront-id'

  CloudFrontDomainName:
    Description: CloudFront domain name
    Value: !GetAtt CloudFrontDistribution.DomainName
    Export:
      Name: !Sub 'growksh-${Environment}-cloudfront-domain'

  CloudFrontUrl:
    Description: CloudFront URL
    Value: !Sub 'https://${CloudFrontDistribution.DomainName}'
    Export:
      Name: !Sub 'growksh-${Environment}-url'

  OriginAccessControlId:
    Description: CloudFront Origin Access Control ID
    Value: !Ref StaticSiteOriginAccessControl
    Export:
      Name: !Sub 'growksh-${Environment}-oac-id'
