AWSTemplateFormatVersion: '2010-09-09'
Description: WAF configuration for CloudFront distribution (must be in us-east-1)

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, prod, ephemeral]
    Description: Environment name

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Environment Configuration
        Parameters:
          - Environment

Resources:
  CloudFrontWebACL:
    Type: AWS::WAFv2::WebACL
    Properties:
      Name: !Sub 'growksh-website-${Environment}-waf'
      Description: !Sub 'WAF for Growksh website ${Environment} CloudFront distribution'
      Scope: CLOUDFRONT
      DefaultAction:
        Allow: {}
      Rules:
        - Name: AWSManagedRulesAmazonIpReputationList
          Priority: 0
          OverrideAction:
            None: {}
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesAmazonIpReputationList
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: AWSManagedRulesAmazonIpReputationList

        - Name: AWSManagedRulesCommonRuleSet
          Priority: 1
          OverrideAction:
            None: {}
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesCommonRuleSet
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: AWSManagedRulesCommonRuleSet

        - Name: AWSManagedRulesKnownBadInputsRuleSet
          Priority: 2
          OverrideAction:
            None: {}
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesKnownBadInputsRuleSet
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: AWSManagedRulesKnownBadInputsRuleSet

        - Name: RateLimitPerIp
          Priority: 3
          Action:
            Block: {}
          Statement:
            RateBasedStatement:
              Limit: 1000
              EvaluationWindowSeconds: 300
              AggregateKeyType: IP
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: RateLimitPerIp

      VisibilityConfig:
        SampledRequestsEnabled: true
        CloudWatchMetricsEnabled: true
        MetricName: !Sub 'growksh-website-${Environment}-waf'
      Tags:
        - Key: App
          Value: Website
        - Key: Partner
          Value: Growksh
        - Key: Env
          Value: !Ref Environment

Outputs:
  WebACLArn:
    Description: WAF Web ACL ARN for CloudFront
    Value: !GetAtt CloudFrontWebACL.Arn
    Export:
      Name: !Sub 'growksh-website-${Environment}-waf-arn'

  WebACLId:
    Description: WAF Web ACL ID
    Value: !Ref CloudFrontWebACL
    Export:
      Name: !Sub 'growksh-website-${Environment}-waf-id'
