AWSTemplateFormatVersion: '2010-09-09'
Description: Contact and Auth API Lambda functions for Growksh website

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, prod, ephemeral]
    Description: Environment name
  SESSourceEmail:
    Type: String
    Description: Verified SES email address
    Default: noreply@growksh.com
  VerifyBaseUrl:
    Type: String
    Description: Frontend URL for email verification
    Default: https://dev.growksh.com/auth/verify-email

Resources:
  ContactFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub 'growksh-website-contact-${Environment}'
      Runtime: nodejs18.x
      Handler: index.handler
      Role: !ImportValue
        Fn::Sub: 'growksh-website-${Environment}-contact-lambda-arn'
      Code:
        S3Bucket: !Sub 'growksh-website-lambda-code-${AWS::AccountId}'
        S3Key: !Sub 'contact/contact-${Environment}.zip'
      Environment:
        Variables:
          CONTACTS_TABLE: !ImportValue
            Fn::Sub: 'growksh-website-${Environment}-contacts-table'
      Tags:
        - Key: App
          Value: Website
        - Key: Partner
          Value: Growksh
        - Key: Env
          Value: !Ref Environment

  ContactFunctionApiPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ContactFunction
      Principal: apigateway.amazonaws.com
      Action: lambda:InvokeFunction
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGateway}/*'

  SignupFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub 'growksh-website-signup-${Environment}'
      Runtime: nodejs18.x
      Handler: signup.handler
      Role: !ImportValue
        Fn::Sub: 'growksh-website-${Environment}-auth-lambda-arn'
      Code:
        S3Bucket: !Sub 'growksh-website-lambda-code-${AWS::AccountId}'
        S3Key: !Sub 'auth/signup-${Environment}.zip'
      Environment:
        Variables:
          COGNITO_USER_POOL_ID: !ImportValue
            Fn::Sub: 'growksh-website-${Environment}-pool-id'
          SES_SOURCE_EMAIL: !Ref SESSourceEmail
          VERIFY_BASE_URL: !Ref VerifyBaseUrl
      Tags:
        - Key: App
          Value: Website
        - Key: Partner
          Value: Growksh
        - Key: Env
          Value: !Ref Environment

  SignupFunctionApiPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref SignupFunction
      Principal: apigateway.amazonaws.com
      Action: lambda:InvokeFunction
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGateway}/*'

  VerifyEmailFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub 'growksh-website-verify-email-${Environment}'
      Runtime: nodejs18.x
      Handler: verify-email.handler
      Role: !ImportValue
        Fn::Sub: 'growksh-website-${Environment}-auth-lambda-arn'
      Code:
        S3Bucket: !Sub 'growksh-website-lambda-code-${AWS::AccountId}'
        S3Key: !Sub 'auth/verify-email-${Environment}.zip'
      Environment:
        Variables:
          COGNITO_USER_POOL_ID: !ImportValue
            Fn::Sub: 'growksh-website-${Environment}-pool-id'
      Tags:
        - Key: App
          Value: Website
        - Key: Partner
          Value: Growksh
        - Key: Env
          Value: !Ref Environment

  VerifyEmailFunctionApiPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref VerifyEmailFunction
      Principal: apigateway.amazonaws.com
      Action: lambda:InvokeFunction
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGateway}/*'

  CheckAdminFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub 'growksh-website-check-admin-${Environment}'
      Runtime: nodejs18.x
      Handler: check-admin.handler
      Role: !ImportValue
        Fn::Sub: 'growksh-website-${Environment}-auth-lambda-arn'
      Code:
        S3Bucket: !Sub 'growksh-website-lambda-code-${AWS::AccountId}'
        S3Key: !Sub 'auth/check-admin-${Environment}.zip'
      Environment:
        Variables:
          COGNITO_USER_POOL_ID: !ImportValue
            Fn::Sub: 'growksh-website-${Environment}-pool-id'
      Tags:
        - Key: App
          Value: Website
        - Key: Partner
          Value: Growksh
        - Key: Env
          Value: !Ref Environment

  CheckAdminFunctionApiPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref CheckAdminFunction
      Principal: apigateway.amazonaws.com
      Action: lambda:InvokeFunction
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGateway}/*'

  ApiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub 'growksh-website-api-${Environment}'

Outputs:
  ContactFunctionArn:
    Value: !GetAtt ContactFunction.Arn
    Export:
      Name: !Sub 'growksh-website-${Environment}-contact-function-arn'

  SignupFunctionArn:
    Value: !GetAtt SignupFunction.Arn
    Export:
      Name: !Sub 'growksh-website-${Environment}-signup-function-arn'

  VerifyEmailFunctionArn:
    Value: !GetAtt VerifyEmailFunction.Arn
    Export:
      Name: !Sub 'growksh-website-${Environment}-verify-email-function-arn'

  CheckAdminFunctionArn:
    Value: !GetAtt CheckAdminFunction.Arn
    Export:
      Name: !Sub 'growksh-website-${Environment}-check-admin-function-arn'
