AWSTemplateFormatVersion: '2010-09-09'
Description: Cognito Lambda triggers for Growksh website

Parameters:
  Environment:
    Type: String
    Default: dev

    Description: Environment name
  LambdaCodeBucketName:
    Type: String
    Description: S3 bucket name containing Lambda function code
    Default: ''
  SESSourceEmail:
    Type: String
    Description: Verified SES email for sending OTPs
    Default: noreply@growksh.com
  VerifyBaseUrl:
    Type: String
    Description: Frontend URL for email verification
    Default: https://dev.growksh.com/auth/verify-email

  VerifySecret:
    Type: String
    Description: Secret used to sign verification links (HMAC). Must match API Lambdas.
    Default: ''
  DebugLogOTP:
    Type: String
    Default: '0'
    Description: Enable OTP debug logging

Resources:
  PreSignUpFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub 'growksh-website-pre-sign-up-${Environment}'
      Runtime: nodejs22.x
      Handler: pre-sign-up.handler
      Role: !ImportValue
        Fn::Sub: 'growksh-website-${Environment}-auth-lambda-role-arn'
      Code:
        S3Bucket: !Ref LambdaCodeBucketName
        S3Key: !Sub 'auth/pre-sign-up-${Environment}.zip'
      Tags:
        - Key: App
          Value: Website
        - Key: Partner
          Value: Growksh
        - Key: Env
          Value: !Ref Environment

  CustomMessageFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub 'growksh-website-custom-message-${Environment}'
      Runtime: nodejs22.x
      Handler: custom-message.handler
      Role: !ImportValue
        Fn::Sub: 'growksh-website-${Environment}-auth-lambda-role-arn'
      Code:
        S3Bucket: !Ref LambdaCodeBucketName
        S3Key: !Sub 'auth/custom-message-${Environment}.zip'
      Environment:
        Variables:
          VERIFY_BASE_URL: !Ref VerifyBaseUrl
          VERIFY_SECRET: !Ref VerifySecret
          DEBUG_LOG: !Ref DebugLogOTP
      Tags:
        - Key: App
          Value: Website
        - Key: Partner
          Value: Growksh
        - Key: Env
          Value: !Ref Environment

  DefineAuthChallengeFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub 'growksh-website-define-auth-challenge-${Environment}'
      Runtime: nodejs22.x
      Handler: define-auth-challenge.handler
      Role: !ImportValue
        Fn::Sub: 'growksh-website-${Environment}-auth-lambda-role-arn'
      Code:
        S3Bucket: !Ref LambdaCodeBucketName
        S3Key: !Sub 'auth/define-auth-challenge-${Environment}.zip'
      Tags:
        - Key: App
          Value: Website
        - Key: Partner
          Value: Growksh
        - Key: Env
          Value: !Ref Environment

  CreateAuthChallengeFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub 'growksh-website-create-auth-challenge-${Environment}'
      Runtime: nodejs22.x
      Handler: create-auth-challenge.handler
      Role: !ImportValue
        Fn::Sub: 'growksh-website-${Environment}-auth-lambda-role-arn'
      Code:
        S3Bucket: !Ref LambdaCodeBucketName
        S3Key: !Sub 'auth/create-auth-challenge-${Environment}.zip'
      Environment:
        Variables:
          OTP_TABLE: !ImportValue
            Fn::Sub: 'growksh-website-${Environment}-auth-otp-table'
          SES_SOURCE_EMAIL: !Ref SESSourceEmail
          DEBUG_LOG: !Ref DebugLogOTP
      Tags:
        - Key: App
          Value: Website
        - Key: Partner
          Value: Growksh
        - Key: Env
          Value: !Ref Environment

  VerifyAuthChallengeFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub 'growksh-website-verify-auth-challenge-${Environment}'
      Runtime: nodejs22.x
      Handler: verify-auth-challenge.handler
      Role: !ImportValue
        Fn::Sub: 'growksh-website-${Environment}-auth-lambda-role-arn'
      Code:
        S3Bucket: !Ref LambdaCodeBucketName
        S3Key: !Sub 'auth/verify-auth-challenge-${Environment}.zip'
      Environment:
        Variables:
          OTP_TABLE: !ImportValue
            Fn::Sub: 'growksh-website-${Environment}-auth-otp-table'
      Tags:
        - Key: App
          Value: Website
        - Key: Partner
          Value: Growksh
        - Key: Env
          Value: !Ref Environment

  PostConfirmationFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub 'growksh-website-post-confirmation-${Environment}'
      Runtime: nodejs22.x
      Handler: post-confirmation.handler
      Role: !ImportValue
        Fn::Sub: 'growksh-website-${Environment}-auth-lambda-role-arn'
      Code:
        S3Bucket: !Ref LambdaCodeBucketName
        S3Key: !Sub 'auth/post-confirmation-${Environment}.zip'
      Tags:
        - Key: App
          Value: Website
        - Key: Partner
          Value: Growksh
        - Key: Env
          Value: !Ref Environment

  # Lambda permissions for Cognito to invoke
  PreSignUpPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref PreSignUpFunction
      Principal: cognito-idp.amazonaws.com
      Action: lambda:InvokeFunction
      SourceArn: !ImportValue
        Fn::Sub: 'growksh-website-${Environment}-pool-arn'

  CustomMessagePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref CustomMessageFunction
      Principal: cognito-idp.amazonaws.com
      Action: lambda:InvokeFunction
      SourceArn: !ImportValue
        Fn::Sub: 'growksh-website-${Environment}-pool-arn'

  DefineAuthChallengePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref DefineAuthChallengeFunction
      Principal: cognito-idp.amazonaws.com
      Action: lambda:InvokeFunction
      SourceArn: !ImportValue
        Fn::Sub: 'growksh-website-${Environment}-pool-arn'

  CreateAuthChallengePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref CreateAuthChallengeFunction
      Principal: cognito-idp.amazonaws.com
      Action: lambda:InvokeFunction
      SourceArn: !ImportValue
        Fn::Sub: 'growksh-website-${Environment}-pool-arn'

  VerifyAuthChallengePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref VerifyAuthChallengeFunction
      Principal: cognito-idp.amazonaws.com
      Action: lambda:InvokeFunction
      SourceArn: !ImportValue
        Fn::Sub: 'growksh-website-${Environment}-pool-arn'

  PostConfirmationPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref PostConfirmationFunction
      Principal: cognito-idp.amazonaws.com
      Action: lambda:InvokeFunction
      SourceArn: !ImportValue
        Fn::Sub: 'growksh-website-${Environment}-pool-arn'

  # Attach Lambda functions to Cognito
  PoolResourceServer:
    Type: AWS::Cognito::UserPoolResourceServer
    Properties:
      UserPoolId: !ImportValue
        Fn::Sub: 'growksh-website-${Environment}-pool-id'
      Identifier: growksh-api
      Name: Growksh API
      Scopes:
        - ScopeName: access
          ScopeDescription: Access to Growksh API

Outputs:
  PreSignUpFunctionArn:
    Value: !GetAtt PreSignUpFunction.Arn
    Export:
      Name: !Sub 'growksh-website-${Environment}-pre-sign-up-arn'

  CreateAuthChallengeFunctionArn:
    Value: !GetAtt CreateAuthChallengeFunction.Arn
    Export:
      Name: !Sub 'growksh-website-${Environment}-create-auth-challenge-arn'

  VerifyAuthChallengeFunctionArn:
    Value: !GetAtt VerifyAuthChallengeFunction.Arn
    Export:
      Name: !Sub 'growksh-website-${Environment}-verify-auth-challenge-arn'
  PostConfirmationFunctionArn:
    Value: !GetAtt PostConfirmationFunction.Arn
    Export:
      Name: !Sub 'growksh-website-${Environment}-post-confirmation-arn'

  CustomMessageFunctionArn:
    Value: !GetAtt CustomMessageFunction.Arn
    Export:
      Name: !Sub 'growksh-website-${Environment}-custom-message-arn'

  DefineAuthChallengeFunctionArn:
    Value: !GetAtt DefineAuthChallengeFunction.Arn
    Export:
      Name: !Sub 'growksh-website-${Environment}-define-auth-challenge-arn'