AWSTemplateFormatVersion: '2010-09-09'
Description: Contact and Auth API Lambda functions for Growksh website

Parameters:
  Environment:
    Type: String
    Default: dev

    Description: Environment name
  LambdaCodeSourceEnv:
    Type: String
    Default: dev
    Description: Environment suffix used when packaging Lambda code (e.g., dev or feature-77d07ae1)
  LambdaCodeBucketName:
    Type: String
    Description: S3 bucket name containing Lambda function code (optional). If empty, the stack will create one.
    Default: ''
  SESSourceEmail:
    Type: String
    Description: Verified SES email address
    Default: noreply@growksh.com
  VerifyBaseUrl:
    Type: String
    Description: Frontend URL for email verification
    Default: https://dev.growksh.com/auth/verify-email

  VerifySecret:
    Type: String
    Description: Secret used to sign verification links (HMAC). Set to a long random value.
    Default: ''

Conditions:
  UseProvidedBucket: !Not [ !Equals [ !Ref LambdaCodeBucketName, '' ] ]
  CreateLambdaCodeBucket: !Equals [ !Ref LambdaCodeBucketName, '' ]

Resources:
  LambdaCodeBucket:
    Condition: CreateLambdaCodeBucket
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'growksh-website-lambda-code-${Environment}-${AWS::Region}'
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
  ContactFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub 'growksh-website-contact-${Environment}'
      Runtime: nodejs22.x
      Handler: index.handler
      Role: !ImportValue
        Fn::Sub: 'growksh-website-${Environment}-contact-lambda-role-arn'
      Code:
        S3Bucket:
          Fn::If:
            - UseProvidedBucket
            - !Ref LambdaCodeBucketName
            - !Ref LambdaCodeBucket
        S3Key: !Sub 'contact/contact-${LambdaCodeSourceEnv}.zip'
      Environment:
        Variables:
          CONTACTS_TABLE: !ImportValue
            Fn::Sub: 'growksh-website-${Environment}-contacts-table'
      Tags:
        - Key: App
          Value: Website
        - Key: Partner
          Value: Growksh
        - Key: Env
          Value: !Ref Environment

  ContactFunctionApiPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ContactFunction
      Principal: apigateway.amazonaws.com
      Action: lambda:InvokeFunction
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:*/*/POST/contact'

  SignupFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub 'growksh-website-signup-${Environment}'
      Runtime: nodejs22.x
      Handler: signup.handler
      Role: !ImportValue
        Fn::Sub: 'growksh-website-${Environment}-auth-lambda-role-arn'
      Code:
        S3Bucket:
          Fn::If:
            - UseProvidedBucket
            - !Ref LambdaCodeBucketName
            - !Ref LambdaCodeBucket
        S3Key: !Sub 'auth/signup-${LambdaCodeSourceEnv}.zip'
      Environment:
        Variables:
          COGNITO_USER_POOL_ID: !ImportValue
            Fn::Sub: 'growksh-website-${Environment}-pool-id'
          SES_SOURCE_EMAIL: !Ref SESSourceEmail
          VERIFY_BASE_URL: !Ref VerifyBaseUrl
          VERIFY_SECRET: !Ref VerifySecret
      Tags:
        - Key: App
          Value: Website
        - Key: Partner
          Value: Growksh
        - Key: Env
          Value: !Ref Environment

  SignupFunctionApiPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref SignupFunction
      Principal: apigateway.amazonaws.com
      Action: lambda:InvokeFunction
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:*/*/POST/auth/signup'

  VerifyEmailFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub 'growksh-website-verify-email-${Environment}'
      Runtime: nodejs22.x
      Handler: verify-email.handler
      Role: !ImportValue
        Fn::Sub: 'growksh-website-${Environment}-auth-lambda-role-arn'
      Code:
        S3Bucket:
          Fn::If:
            - UseProvidedBucket
            - !Ref LambdaCodeBucketName
            - !Ref LambdaCodeBucket
        S3Key: !Sub 'auth/verify-email-${LambdaCodeSourceEnv}.zip'
      Environment:
        Variables:
          COGNITO_USER_POOL_ID: !ImportValue
            Fn::Sub: 'growksh-website-${Environment}-pool-id'
          VERIFY_SECRET: !Ref VerifySecret

  CheckUserFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub 'growksh-website-check-user-${Environment}'
      Runtime: nodejs22.x
      Handler: check-user.handler
      Role: !ImportValue
        Fn::Sub: 'growksh-website-${Environment}-auth-lambda-role-arn'
      Code:
        S3Bucket:
          Fn::If:
            - UseProvidedBucket
            - !Ref LambdaCodeBucketName
            - !Ref LambdaCodeBucket
        S3Key: !Sub 'auth/check-user-${LambdaCodeSourceEnv}.zip'
      Environment:
        Variables:
          COGNITO_USER_POOL_ID: !ImportValue
            Fn::Sub: 'growksh-website-${Environment}-pool-id'
      Tags:
        - Key: App
          Value: Website
        - Key: Partner
          Value: Growksh
        - Key: Env
          Value: !Ref Environment

  CheckUserFunctionApiPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref CheckUserFunction
      Principal: apigateway.amazonaws.com
      Action: lambda:InvokeFunction
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:*/*/POST/auth/check-user'

  ResendVerificationFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub 'growksh-website-resend-verification-${Environment}'
      Runtime: nodejs22.x
      Handler: resend-verification.handler
      Role: !ImportValue
        Fn::Sub: 'growksh-website-${Environment}-auth-lambda-role-arn'
      Code:
        S3Bucket:
          Fn::If:
            - UseProvidedBucket
            - !Ref LambdaCodeBucketName
            - !Ref LambdaCodeBucket
        S3Key: !Sub 'auth/resend-verification-${LambdaCodeSourceEnv}.zip'
      Environment:
        Variables:
          COGNITO_USER_POOL_ID: !ImportValue
            Fn::Sub: 'growksh-website-${Environment}-pool-id'
          SES_SOURCE_EMAIL: !Ref SESSourceEmail
          VERIFY_BASE_URL: !Ref VerifyBaseUrl
          VERIFY_SECRET: !Ref VerifySecret
      Tags:
        - Key: App
          Value: Website
        - Key: Partner
          Value: Growksh
        - Key: Env
          Value: !Ref Environment

  ResendVerificationFunctionApiPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ResendVerificationFunction
      Principal: apigateway.amazonaws.com
      Action: lambda:InvokeFunction
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:*/*/POST/auth/resend-verification'

  ListUsersFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub 'growksh-website-list-users-${Environment}'
      Runtime: nodejs22.x
      Handler: list-users.handler
      Role: !ImportValue
        Fn::Sub: 'growksh-website-${Environment}-auth-lambda-role-arn'
      Code:
        S3Bucket:
          Fn::If:
            - UseProvidedBucket
            - !Ref LambdaCodeBucketName
            - !Ref LambdaCodeBucket
        S3Key: !Sub 'auth/list-users-${LambdaCodeSourceEnv}.zip'
      Environment:
        Variables:
          COGNITO_USER_POOL_ID: !ImportValue
            Fn::Sub: 'growksh-website-${Environment}-pool-id'
          COGNITO_CLIENT_ID: !ImportValue
            Fn::Sub: 'growksh-website-client-${Environment}-id'
      Tags:
        - Key: App
          Value: Website
        - Key: Partner
          Value: Growksh
        - Key: Env
          Value: !Ref Environment

  ListUsersFunctionApiPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ListUsersFunction
      Principal: apigateway.amazonaws.com
      Action: lambda:InvokeFunction
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:*/*/GET/auth/list-users'

  VerifyEmailFunctionApiPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref VerifyEmailFunction
      Principal: apigateway.amazonaws.com
      Action: lambda:InvokeFunction
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:*/*/GET/auth/verify-email'

  CheckAdminFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub 'growksh-website-check-admin-${Environment}'
      Runtime: nodejs22.x
      Handler: define-auth-challenge.handler
      Role: !ImportValue
        Fn::Sub: 'growksh-website-${Environment}-auth-lambda-role-arn'
      Code:
        S3Bucket:
          Fn::If:
            - UseProvidedBucket
            - !Ref LambdaCodeBucketName
            - !Ref LambdaCodeBucket
        S3Key: !Sub 'auth/check-admin-${LambdaCodeSourceEnv}.zip'
      Environment:
        Variables:
          COGNITO_USER_POOL_ID: !ImportValue
            Fn::Sub: 'growksh-website-${Environment}-pool-id'
      Tags:
        - Key: App
          Value: Website
        - Key: Partner
          Value: Growksh
        - Key: Env
          Value: !Ref Environment

  CheckAdminFunctionApiPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref CheckAdminFunction
      Principal: apigateway.amazonaws.com
      Action: lambda:InvokeFunction
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:*/*/POST/auth/check-admin'


Outputs:
  ContactFunctionArn:
    Value: !GetAtt ContactFunction.Arn
    Export:
      Name: !Sub 'growksh-website-${Environment}-contact-lambda-arn'

  SignupFunctionArn:
    Value: !GetAtt SignupFunction.Arn
    Export:
      Name: !Sub 'growksh-website-${Environment}-signup-lambda-arn'

  VerifyEmailFunctionArn:
    Value: !GetAtt VerifyEmailFunction.Arn
    Export:
      Name: !Sub 'growksh-website-${Environment}-verify-email-lambda-arn'

  CheckUserFunctionArn:
    Value: !GetAtt CheckUserFunction.Arn
    Export:
      Name: !Sub 'growksh-website-${Environment}-check-user-lambda-arn'

  ResendVerificationFunctionArn:
    Value: !GetAtt ResendVerificationFunction.Arn
    Export:
      Name: !Sub 'growksh-website-${Environment}-resend-verification-lambda-arn'

  ListUsersFunctionArn:
    Value: !GetAtt ListUsersFunction.Arn
    Export:
      Name: !Sub 'growksh-website-${Environment}-list-users-lambda-arn'

  CheckAdminFunctionArn:
    Value: !GetAtt CheckAdminFunction.Arn
    Export:
      Name: !Sub 'growksh-website-${Environment}-check-admin-lambda-arn'
