AWSTemplateFormatVersion: '2010-09-09'
Description: |
  Amazon SES Configuration for Growksh Email Sending
  - Email identity verification
  - Email templates for OTP and magic links
  - Configuration set for email tracking and bounce handling

Parameters:
  Environment:
    Type: String
    Description: Environment name (dev, staging, prod)
    AllowedValues:
      - dev
      - staging
      - prod
    Default: dev

  FromEmailAddress:
    Type: String
    Description: Verified sender email address for Growksh
    AllowedPattern: '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'

Resources:
  # Email Identity for Growksh
  VerifiedEmailIdentity:
    Type: AWS::SES::VerifiedEmailIdentity
    Properties:
      EmailAddress: !Ref FromEmailAddress

  # Configuration Set for Email Delivery Tracking
  SESConfigurationSet:
    Type: AWS::SES::ConfigurationSet
    Properties:
      Name: !Sub 'growksh-${Environment}-config-set'

  # Event Destination for Bounce Handling
  SESConfigurationSetEventDestination:
    Type: AWS::SES::ConfigurationSetEventDestination
    Properties:
      ConfigurationSetName: !Ref SESConfigurationSet
      EventDestination:
        Name: !Sub 'growksh-${Environment}-bounce-destination'
        Enabled: true
        MatchingEventTypes:
          - bounce
          - complaint
        CloudWatchDestination:
          IAMRoleArn: !GetAtt SESCloudWatchRole.Arn
          DimensionConfigurations:
            - DimensionName: Configuration Set
              DimensionValueSource: MessageTag
              DefaultDimensionValue: default

  # CloudWatch Log Group for Email Bounces
  SESBounceLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/ses/growksh/${Environment}/bounces'
      RetentionInDays: 30

  # SNS Topic for Email Delivery Notifications
  SESNotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub 'growksh-${Environment}-ses-notifications'
      DisplayName: Growksh SES Email Notifications

  # Email Template for OTP Verification
  OTPEmailTemplate:
    Type: AWS::SES::Template
    Properties:
      Template:
        TemplateName: !Sub 'growksh-${Environment}-otp-verification'
        SubjectPart: 'Your Growksh OTP Code'
        HtmlPart: |
          <!DOCTYPE html>
          <html>
          <head>
            <meta charset="UTF-8">
            <style>
              body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
              .container { max-width: 600px; margin: 0 auto; padding: 20px; }
              .header { background-color: #4CAF50; color: white; padding: 20px; text-align: center; }
              .content { padding: 20px; background-color: #f9f9f9; }
              .otp-code { font-size: 32px; font-weight: bold; text-align: center; color: #4CAF50; padding: 20px; letter-spacing: 2px; }
              .footer { text-align: center; padding: 20px; font-size: 12px; color: #666; }
            </style>
          </head>
          <body>
            <div class="container">
              <div class="header">
                <h1>Growksh Verification</h1>
              </div>
              <div class="content">
                <p>Hello {{username}},</p>
                <p>Your one-time password (OTP) for Growksh is:</p>
                <div class="otp-code">{{otp_code}}</div>
                <p>This OTP will expire in <strong>{{expiry_minutes}} minutes</strong>.</p>
                <p>If you didn't request this code, please ignore this email.</p>
              </div>
              <div class="footer">
                <p>&copy; 2026 Growksh. All rights reserved.</p>
              </div>
            </div>
          </body>
          </html>
        TextPart: |
          Hello {{username}},
          
          Your one-time password (OTP) for Growksh is:
          
          {{otp_code}}
          
          This OTP will expire in {{expiry_minutes}} minutes.
          
          If you didn't request this code, please ignore this email.
          
          Best regards,
          Growksh Team

  # Email Template for Magic Link Verification
  MagicLinkEmailTemplate:
    Type: AWS::SES::Template
    Properties:
      Template:
        TemplateName: !Sub 'growksh-${Environment}-magic-link-verification'
        SubjectPart: 'Verify your email for Growksh'
        HtmlPart: |
          <!DOCTYPE html>
          <html>
          <head>
            <meta charset="UTF-8">
            <style>
              body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
              .container { max-width: 600px; margin: 0 auto; padding: 20px; }
              .header { background-color: #4CAF50; color: white; padding: 20px; text-align: center; }
              .content { padding: 20px; background-color: #f9f9f9; }
              .button { display: inline-block; padding: 12px 24px; background-color: #4CAF50; color: white; text-decoration: none; border-radius: 4px; margin: 20px 0; }
              .footer { text-align: center; padding: 20px; font-size: 12px; color: #666; }
            </style>
          </head>
          <body>
            <div class="container">
              <div class="header">
                <h1>Verify Your Email</h1>
              </div>
              <div class="content">
                <p>Hello {{username}},</p>
                <p>Welcome to Growksh! To complete your signup, please click the button below to verify your email:</p>
                <div style="text-align: center;">
                  <a href="{{verification_link}}" class="button">Verify Email</a>
                </div>
                <p>Or copy and paste this link in your browser:</p>
                <p><code>{{verification_link}}</code></p>
                <p>This link will expire in <strong>24 hours</strong>.</p>
                <p>If you didn't create this account, please ignore this email.</p>
              </div>
              <div class="footer">
                <p>&copy; 2026 Growksh. All rights reserved.</p>
              </div>
            </div>
          </body>
          </html>
        TextPart: |
          Hello {{username}},
          
          Welcome to Growksh! To complete your signup, please click the link below to verify your email:
          
          {{verification_link}}
          
          This link will expire in 24 hours.
          
          If you didn't create this account, please ignore this email.
          
          Best regards,
          Growksh Team

  # Email Template for Password Reset
  PasswordResetEmailTemplate:
    Type: AWS::SES::Template
    Properties:
      Template:
        TemplateName: !Sub 'growksh-${Environment}-password-reset'
        SubjectPart: 'Reset your Growksh password'
        HtmlPart: |
          <!DOCTYPE html>
          <html>
          <head>
            <meta charset="UTF-8">
            <style>
              body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
              .container { max-width: 600px; margin: 0 auto; padding: 20px; }
              .header { background-color: #FF9800; color: white; padding: 20px; text-align: center; }
              .content { padding: 20px; background-color: #f9f9f9; }
              .button { display: inline-block; padding: 12px 24px; background-color: #FF9800; color: white; text-decoration: none; border-radius: 4px; margin: 20px 0; }
              .footer { text-align: center; padding: 20px; font-size: 12px; color: #666; }
            </style>
          </head>
          <body>
            <div class="container">
              <div class="header">
                <h1>Password Reset Request</h1>
              </div>
              <div class="content">
                <p>Hello {{username}},</p>
                <p>We received a request to reset your Growksh password. Click the button below to reset it:</p>
                <div style="text-align: center;">
                  <a href="{{reset_link}}" class="button">Reset Password</a>
                </div>
                <p>Or copy and paste this link in your browser:</p>
                <p><code>{{reset_link}}</code></p>
                <p>This link will expire in <strong>1 hour</strong>.</p>
                <p>If you didn't request a password reset, please ignore this email.</p>
              </div>
              <div class="footer">
                <p>&copy; 2026 Growksh. All rights reserved.</p>
              </div>
            </div>
          </body>
          </html>
        TextPart: |
          Hello {{username}},
          
          We received a request to reset your Growksh password. Click the link below to reset it:
          
          {{reset_link}}
          
          This link will expire in 1 hour.
          
          If you didn't request a password reset, please ignore this email.
          
          Best regards,
          Growksh Team

Outputs:
  SESConfigurationSetName:
    Description: SES Configuration Set Name
    Value: !Ref SESConfigurationSet
    Export:
      Name: !Sub 'growksh-${Environment}-ses-config-set-name'

  VerifiedEmailIdentity:
    Description: Verified Email Identity for sending
    Value: !Ref VerifiedEmailIdentity
    Export:
      Name: !Sub 'growksh-${Environment}-verified-email'

  SESNotificationTopicArn:
    Description: SNS Topic for SES notifications
    Value: !Ref SESNotificationTopic
    Export:
      Name: !Sub 'growksh-${Environment}-ses-notification-topic'

  OTPTemplateId:
    Description: SES Template ID for OTP emails
    Value: !Sub 'growksh-${Environment}-otp-verification'
    Export:
      Name: !Sub 'growksh-${Environment}-otp-template-id'

  MagicLinkTemplateId:
    Description: SES Template ID for Magic Link emails
    Value: !Sub 'growksh-${Environment}-magic-link-verification'
    Export:
      Name: !Sub 'growksh-${Environment}-magic-link-template-id'

  PasswordResetTemplateId:
    Description: SES Template ID for Password Reset emails
    Value: !Sub 'growksh-${Environment}-password-reset'
    Export:
      Name: !Sub 'growksh-${Environment}-password-reset-template-id'

  BounceLogGroupName:
    Description: CloudWatch Log Group for SES bounces
    Value: !Ref SESBounceLogGroup
    Export:
      Name: !Sub 'growksh-${Environment}-ses-bounce-logs'
