AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM template for Contact API with Email Verification

Parameters:
  SESSourceEmail:
    Type: String
    Description: "Verified SES source email address for sending verification emails"
    Default: "noreply@growksh.com"
  VerifyBaseUrl:
    Type: String
    Description: "Frontend URL where users will verify their email"
    Default: "https://growksh.com/auth/verify-email"
  VerifySecret:
    Type: String
    Description: "HMAC secret for signing verification tokens"
    Default: "change-me-replace-with-a-long-secret"

Globals:
  Function:
    Timeout: 10

Resources:
  ContactsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${AWS::StackName}-contacts"
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  ContactFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs18.x
      CodeUri: ../aws-lambda/contact/
      Environment:
        Variables:
          CONTACTS_TABLE: !Ref ContactsTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ContactsTable
      Events:
        ContactPostEvent:
          Type: Api
          Properties:
            Path: /contact
            Method: post
            RestApiId: !Ref ContactApiGateway
        ContactOptionsEvent:
          Type: Api
          Properties:
            Path: /contact
            Method: options
            RestApiId: !Ref ContactApiGateway

  ContactApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      TracingEnabled: true
      Cors:
        AllowMethods: "'GET,POST,OPTIONS,PUT,DELETE'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowOrigin: "'*'"

  # Cognito User Pool with email verification
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub "${AWS::StackName}-userpool"
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email
      Schema:
        - Name: name
          Required: false
          Mutable: true
        - Name: phone_number
          Required: false
          Mutable: true
      VerificationMessageTemplate:
        DefaultEmailOption: CONFIRM_WITH_LINK
        EmailMessage: "Please verify your email by clicking this link: {##Verify Email##}"
        EmailSubject: "Verify your email"
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireUppercase: true
          RequireNumbers: true
          RequireSymbols: false
          TemporaryPasswordValidityDays: 7

  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub "${AWS::StackName}-client"
      UserPoolId: !Ref CognitoUserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      PreventUserExistenceErrors: ENABLED

  # User registration API with email verification
  UserRegisterFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs18.x
      CodeUri: ../aws-lambda/user-register/
      Environment:
        Variables:
          USER_POOL_ID: !Ref CognitoUserPool
          SES_SOURCE_EMAIL: !Ref SESSourceEmail
          VERIFY_BASE_URL: !Ref VerifyBaseUrl
          VERIFY_SECRET: !Ref VerifySecret
          DEBUG_LOG_VERIFY: '0'
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - cognito-idp:AdminCreateUser
                - cognito-idp:AdminUpdateUserAttributes
              Resource: !GetAtt CognitoUserPool.Arn
            - Effect: Allow
              Action:
                - ses:SendEmail
                - ses:SendRawEmail
              Resource: '*'
      Events:
        RegisterApi:
          Type: Api
          Properties:
            Path: /auth/register
            Method: post
            RestApiId: !Ref ContactApiGateway
        RegisterOptions:
          Type: Api
          Properties:
            Path: /auth/register
            Method: options
            RestApiId: !Ref ContactApiGateway

  # Email verification endpoint
  VerifyEmailFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs18.x
      CodeUri: ../aws-lambda/verify-email/
      Environment:
        Variables:
          USER_POOL_ID: !Ref CognitoUserPool
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - cognito-idp:AdminConfirmSignUp
                - cognito-idp:AdminGetUser
                - cognito-idp:AdminUpdateUserAttributes
              Resource: !GetAtt CognitoUserPool.Arn
      Events:
        VerifyEmailApi:
          Type: Api
          Properties:
            Path: /auth/verify-email
            Method: get
            RestApiId: !Ref ContactApiGateway
        VerifyEmailOptions:
          Type: Api
          Properties:
            Path: /auth/verify-email
            Method: options
            RestApiId: !Ref ContactApiGateway

  # Login API (after email verification)
  UserLoginFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs18.x
      CodeUri: ../aws-lambda/user-login/
      Environment:
        Variables:
          USER_POOL_ID: !Ref CognitoUserPool
          COGNITO_CLIENT_ID: !Ref CognitoUserPoolClient
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - cognito-idp:InitiateAuth
              Resource: '*'
      Events:
        LoginApi:
          Type: Api
          Properties:
            Path: /auth/login
            Method: post
            RestApiId: !Ref ContactApiGateway
        LoginOptions:
          Type: Api
          Properties:
            Path: /auth/login
            Method: options
            RestApiId: !Ref ContactApiGateway

Outputs:
  ContactApiEndpoint:
    Description: "API Gateway endpoint"
    Value: !Sub "https://${ContactApiGateway}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  ContactsTableName:
    Description: "DynamoDB table name for contacts"
    Value: !Ref ContactsTable
  CognitoUserPoolId:
    Description: "Cognito User Pool ID"
    Value: !Ref CognitoUserPool
  CognitoUserPoolClientId:
    Description: "Cognito User Pool Client ID"
    Value: !Ref CognitoUserPoolClient
  UserRegisterEndpoint:
    Description: "Registration endpoint"
    Value: !Sub "https://${ContactApiGateway}.execute-api.${AWS::Region}.amazonaws.com/Prod/auth/register"
  VerifyEmailEndpoint:
    Description: "Email verification endpoint"
    Value: !Sub "https://${ContactApiGateway}.execute-api.${AWS::Region}.amazonaws.com/Prod/auth/verify-email"
  UserLoginEndpoint:
    Description: "Login endpoint"
    Value: !Sub "https://${ContactApiGateway}.execute-api.${AWS::Region}.amazonaws.com/Prod/auth/login"