AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM template to deploy Contact API (Lambda) + DynamoDB

Globals:
  Function:
    Timeout: 10

Resources:
  ContactsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${AWS::StackName}-contacts"
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  ContactFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}-contact-handler"
      Handler: index.handler
      Runtime: nodejs18.x
      CodeUri: ../aws-lambda/contact/
      Environment:
        Variables:
          CONTACTS_TABLE: !Ref ContactsTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ContactsTable
      Events:
        ContactApi:
          Type: Api
          Properties:
            Path: /contact
            Method: post
            RestApiId: !Ref ContactApiGateway
    Metadata:
      BuildMethod: makefile

  ContactApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      # Minimal CORS config - just allow all origins for preflight and requests
      # Lambda will provide additional CORS headers in responses
      DefinitionBody:
        openapi: '3.0.0'
        info:
          title: Contact API
          version: '1.0'
        paths:
          /contact:
            post:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ContactFunction.Arn}/invocations
              responses:
                '200':
                  description: Success
                  headers:
                    Access-Control-Allow-Origin:
                      schema:
                        type: string
            options:
              x-amazon-apigateway-integration:
                type: mock
                responses:
                  default:
                    statusCode: 200
                    responseParameters:
                      method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
                      method.response.header.Access-Control-Allow-Methods: "'POST,OPTIONS'"
                      method.response.header.Access-Control-Allow-Origin: "'*'"
              responses:
                '200':
                  description: CORS preflight response
                  headers:
                    Access-Control-Allow-Headers:
                      schema:
                        type: string
                    Access-Control-Allow-Methods:
                      schema:
                        type: string
                    Access-Control-Allow-Origin:
                      schema:
                        type: string

  # Grant API Gateway permission to invoke the Lambda
  ContactFunctionApiPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ContactFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ContactApiGateway}/*/*"

Outputs:
  ContactApiEndpoint:
    Description: "Invoke URL for contact API"
    Value: !Sub "https://${ContactApiGateway}.execute-api.${AWS::Region}.amazonaws.com/Prod/contact"
  ContactsTableName:
    Description: "DynamoDB table name for contacts"
    Value: !Ref ContactsTable
