.PHONY: build-SignupFunction build-VerifyEmailFunction build-PreSignUpFunction build-CustomMessageFunction build-CreateAuthChallengeFunction build-VerifyAuthChallengeFunction build-PostConfirmationFunction

build-SignupFunction:
	npm install --production
	mkdir -p "$(ARTIFACTS_DIR)"
	cp -r . "$(ARTIFACTS_DIR)/"

build-VerifyEmailFunction:
	npm install --production
	mkdir -p "$(ARTIFACTS_DIR)"
	cp -r . "$(ARTIFACTS_DIR)/"

build-PreSignUpFunction:
	npm install --production
	mkdir -p "$(ARTIFACTS_DIR)"
	cp -r . "$(ARTIFACTS_DIR)/"

build-CustomMessageFunction:
	npm install --production
	mkdir -p "$(ARTIFACTS_DIR)"
	cp -r . "$(ARTIFACTS_DIR)/"

build-CreateAuthChallengeFunction:
	npm install --production
	mkdir -p "$(ARTIFACTS_DIR)"
	cp -r . "$(ARTIFACTS_DIR)/"

build-VerifyAuthChallengeFunction:
	npm install --production
	mkdir -p "$(ARTIFACTS_DIR)"
	cp -r . "$(ARTIFACTS_DIR)/"

build-PostConfirmationFunction:
	npm install --production
	mkdir -p "$(ARTIFACTS_DIR)"
	cp -r . "$(ARTIFACTS_DIR)/"
